import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { readBackupManifest } from '../operations/common.js'
import { PilotApi } from './api.js'
import { readPilotManifest, sourceSnapshot, validatePilotManifest } from './manifest.js'

interface Check { name: string; passed: boolean; detail: string }
export interface ReadinessOptions { manifestPath: string; initializationReceiptPath: string; backupPath: string; restoreDrillReportPath: string; qualityGateReportPath: string; apiBaseUrl?: string; reportDirectory?: string; freeze?: boolean; simulationFreeze?: boolean }
export async function pilotReadiness(root: string, options: ReadinessOptions): Promise<{ decision: string; report: string }> {
  if (options.freeze && options.simulationFreeze) throw new Error('--freeze and --simulation-freeze are mutually exclusive')
  const manifest = readPilotManifest(resolve(root, options.manifestPath)); const level = options.freeze ? 'freeze' : options.simulationFreeze ? 'simulation-freeze' : 'initialization'; const validation = validatePilotManifest(manifest, level)
  const receipt = JSON.parse(readFileSync(resolve(root, options.initializationReceiptPath), 'utf8')); const backupPath = resolve(root, options.backupPath); const backup = readBackupManifest(backupPath, true); const restoreReport = readFileSync(resolve(root, options.restoreDrillReportPath), 'utf8'); const qualityReport = readFileSync(resolve(root, options.qualityGateReportPath), 'utf8')
  const checks: Check[] = []; const add = (name: string, passed: boolean, detail: string): void => { checks.push({ name, passed, detail }) }
  add(`manifest-${level}`, validation.valid, validation.valid ? 'manifest contract passed' : validation.errors.join('; ')); add('initialization-receipt', receipt.decision === 'APPLIED' && receipt.pilotId === manifest.pilotId && receipt.targetProject === manifest.environment.projectName, `decision=${receipt.decision}`); add('backup-source', backup.projectName === manifest.environment.projectName, `project=${backup.projectName}`); add('restore-drill', /^- Decision: PASS\s*$/m.test(restoreReport) && restoreReport.includes(backupPath), 'selected backup restored in isolated drill'); add('quality-gate', /^- Status: PASS\s*$/m.test(qualityReport), 'quality gate reports PASS')
  const username = process.env.COLLA_PILOT_ADMIN_USERNAME; const password = process.env.COLLA_PILOT_ADMIN_PASSWORD
  if (!username || !password) add('api-session', false, 'pilot admin environment credentials are required')
  else try {
    const api = new PilotApi(options.apiBaseUrl ?? manifest.environment.baseUrl); const health = await api.request<any>('GET', '/health'); const session = await api.request<any>('POST', '/auth/login', { username, password, deviceType: 'web', deviceFingerprint: `pilot-v2-readiness-${manifest.pilotId}`, deviceName: 'PILOT-V2 readiness', appVersion: 'pilot-v2' }); const authenticated = api.withToken(session.accessToken); add('api-session', health.status === 'ok' && Boolean(session.accessToken), 'health and authenticated session passed')
    const project = (await authenticated.request<any[]>('GET', '/projects')).find((item) => item.projectKey === manifest.templates.project.projectKey)
    if (!project) add('open-p0-p1', false, 'pilot project not found'); else { const urgent = await authenticated.request<any[]>('GET', `/projects/${project.id}/issues?priority=urgent`); const high = await authenticated.request<any[]>('GET', `/projects/${project.id}/issues?priority=high`); const open = [...urgent, ...high].filter((item) => !['done', 'closed', 'rejected'].includes(item.status)); add('open-p0-p1', open.length === 0, `open urgent/high issues=${open.length}`) }
  } catch (error) { add('api-runtime', false, error instanceof Error ? error.message : String(error)) }
  if (options.freeze) { const head = (await import('../lib/git.js')).gitHead(root); const dirty = (await import('../lib/git.js')).gitStatusPaths(root); add('release-commit', dirty.length === 0 && head === manifest.kickoffApproval.releaseCommit && head === backup.sourceGitCommit, `clean=${dirty.length === 0}, head=${head}`) }
  if (options.simulationFreeze) { add('simulation-source-snapshot', sourceSnapshot(root) === manifest.kickoffApproval.sourceSnapshot, 'current snapshot matches kickoff'); add('simulation-backup-manifest', resolve(manifest.kickoffApproval.backupManifest) === join(backupPath, 'manifest.json'), 'selected backup matches kickoff'); add('simulation-release-commit', manifest.kickoffApproval.releaseCommit === backup.sourceGitCommit, 'backup commit matches kickoff') }
  const blocked = checks.some((item) => !item.passed); const decision = blocked ? 'BLOCKED' : options.freeze ? 'READY' : options.simulationFreeze ? 'SIMULATION-READY' : 'REHEARSAL-READY'
  const directory = resolve(root, options.reportDirectory ?? '.local-reports'); mkdirSync(directory, { recursive: true }); const stamp = new Date().toISOString().replace(/[-:]/g, '').replace(/\.\d{3}Z$/, ''); const json = join(directory, `pilot-v2-readiness-${stamp}.json`); const report = join(directory, `pilot-v2-readiness-${stamp}.md`)
  writeFileSync(json, JSON.stringify({ schemaVersion: 1, pilotId: manifest.pilotId, mode: level, decision, checkedAt: new Date().toISOString(), checks }, null, 2)); writeFileSync(report, ['# PILOT-V2 Readiness', '', `- Pilot: ${manifest.pilotId}`, `- Mode: ${level}`, `- Decision: ${decision}`, '', '| Check | Result | Detail |', '| --- | --- | --- |', ...checks.map((item) => `| ${item.name} | ${item.passed ? 'PASS' : 'BLOCKED'} | ${item.detail.replaceAll('|', '\\|')} |`), ''].join('\n')); return { decision, report }
}
